version: '0.2'
phases: 
    install: 
        runtime-versions:
            nodejs: 10
        commands: 
            - 'echo "--------INSTALL PHASE--------"'
            - 'npm install -g aws-cdk'
            - 'pip3 install -r requirements.txt'
            - 'mkdir build'
    build:
        commands:
            - 'echo "--------BUILD PHASE--------"'
            - 'echo "----- Doing cdk synth -----"'
            - 'cdk synth --no-staging >  template.yaml'
            - 'echo "starting SAM build to bundle assets"'
            - 'sam build -t template.yaml -b build'
            - 'echo "Starting SAM packaging `date` in `pwd`"'
            - 'sam package --template-file template.yaml --s3-bucket $BUILD_ARTIFACT_BUCKET --output-template-file packaged.yaml'
artifacts:
    files: 
        - 'packaged.yaml'
    discard-paths: 'yes'
cache:
    paths:
        - '/root/.cache/pip'